apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    release: prom
  name: istio-sidecars
spec:
  selector:
    matchLabels:
      security.istio.io/tlsMode: 'istio'
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
